from hellbot import bot as OFFICIALHACKER

x = True


@bot.on(admin_cmd(pattern="abuse"))
async def yashraid(event):
    while x != False:

        await event.delete()
        kek = event.chat_id
        await OFFICIALHACKER .send_message(kek, "TERI RANDI MAA SE PUCHNA BAAP KA NAAM BAHEN KE LODEEEEE 🤩🥳😳")
        await OFFICIALHACKER .send_message(kek, "TU AUR TERI MAA DONO KI BHOSDE MEI METRO CHALWA DUNGA MADARXHOD 🚇🤩😱🥶")
        await OFFICIALHACKER .send_message(kek, "MAAAAA KAAA KA BHOSDAAAAA KAAA JHOPADA BANAAA DUNGAAAA")
        await OFFICIALHACKER .send_message(kek, "TERI BHAN KA BOROSHA MERA LUND 😁")
        await OFFICIALHACKER .send_message(kek, "EK DORA HAI EK NORA HAI CHARO TARAF KOHRA HI KOHRA AUR TU SABSE BADA BEHAN KA LAWDA HAI 😐")
        await OFFICIALHACKER .send_message(kek, "MERI JANEMAN PURANI BAATE BHOOL JA AURR MERA LUND PAKAD KE JHOOL JA 🤣😂")
        await OFFICIALHACKER .send_message(kek, "JINDAGI KI NA TOOTE LARI TERI LULLI HOTI NHI KHADI 😶")
        await OFFICIALHACKER .send_message(kek, "🙂")
        await OFFICIALHACKER .send_message(kek, "🤣")
        await OFFICIALHACKER .send_message(kek, "MAJDUR KO KHODNA AUR APNE BAAP OFFICIAL HACKER KO CHODNA NAHIN SIKHATE HAIN 🤧")
        await OFFICIALHACKER .send_message(kek, "TO CHALIYE SHURU KARTE HAIN 🤧")
        await OFFICIALHACKER .send_message(kek, "https://te.legra.ph/file/8554b47aa7c1fb50b5214.mp4")
        await OFFICIALHACKER .send_message(kek, "TERI MA KE JHOPDA ME AAAG LAGA DUNGA ")
        await OFFICIALHACKER .send_message(kek, "https://te.legra.ph/file/627f51cae273329dc67d5.mp4")
        await OFFICIALHACKER .send_message(kek, "TERI MA KE BHOSDE ME OFFICIAL HACKER KA LUND ")
        await OFFICIALHACKER .send_message(kek, "TERI MA KI CHOOXT MAARUU BSDKEE")
        await OFFICIALHACKER .send_message(kek, "TERI BHN KA BHOSXDA FAAD DIA MADARCHOD")
        await OFFICIALHACKER .send_message(kek, "TERI BHN KI GANXD ME DYNAMTE LAGA KE UDA DIA")
        await OFFICIALHACKER .send_message(kek, "OFFICIAL HACKER  OP HAI HM BAAP BOLTE HMKO")
        await OFFICIALHACKER .send_message(kek, "TERI MAA KO CHOODUU")
        await OFFICIALHACKER .send_message(kek, "MAADARCHODD")
        await OFFICIALHACKER .send_message(kek, "😂")
        await OFFICIALHACKER .send_message(kek, "ROJJ MERE")
        await OFFICIALHACKER .send_message(kek, "LODEE PE")
        await OFFICIALHACKER .send_message(kek, "AAKEE UCHALTII")
        await OFFICIALHACKER .send_message(kek, "HAII")
        await OFFICIALHACKER .send_message(kek, "TERI GANND TOD DI JAYEGI MADDRCHOOD")
        await OFFICIALHACKER .send_message(kek, "😂")
        await OFFICIALHACKER .send_message(kek, "TERI MAA KA BHOOSSDA FAADU DOGLE MADRCHODD")
        await OFFICIALHACKER .send_message(kek, "BEHEN")
        await OFFICIALHACKER .send_message(kek, "KII CHUTTT")
        await OFFICIALHACKER .send_message(kek, "AUR GANND")
        await OFFICIALHACKER .send_message(kek, "MAR MARKE")
        await OFFICIALHACKER .send_message(kek, "EK KAR DIYAA")
        await OFFICIALHACKER .send_message(kek, "OFFICIAL HACKER  MEMBER IS ALWAYS ON FIRE")
        await OFFICIALHACKER .send_message(kek, "😂")
        await OFFICIALHACKER .send_message(kek, "MADERRRRCHODDO")
        await OFFICIALHACKER .send_message(kek, "TUM SABB KAA")
        await OFFICIALHACKER .send_message(kek, " BAAAP HAII")
        await OFFICIALHACKER .send_message(
            kek, "OFFICIAL HACKER  HAI HM HMKO KAHTE H OP AUR BETE TUM OFFICIAL HACKER  KE LAND KI TOPI"
        )
        await OFFICIALHACKER .send_message(kek, "😂")
        await OFFICIALHACKER .send_message(kek, "TERI GAMD TOD DI JAYEGI MADDRCHOD")
        await OFFICIALHACKER .send_message(kek, "KII MAA")
        await OFFICIALHACKER .send_message(kek, "KAA RAPEE")
        await OFFICIALHACKER .send_message(kek, "KR DIYAA")
        await OFFICIALHACKER .send_message(kek, "EKDUM GHODII")
        await OFFICIALHACKER .send_message(kek, "BANAKEE")
        await OFFICIALHACKER .send_message(kek, " CHODAA")
        await OFFICIALHACKER .send_message(kek, "OFFICIAL HACKER  NE CHOD DIA TUJE")
        await OFFICIALHACKER .send_message(kek, "😂")
        await OFFICIALHACKER .send_message(kek, "https://te.legra.ph/file/5bbf6abbac75052594c1a.mp4")
        await OFFICIALHACKER .send_message(kek, "TUMHARII MAA KO")
        await OFFICIALHACKER .send_message(kek, "AISAA")
        await OFFICIALHACKER .send_message(kek, "ALE ALE MERA BETA 😂")
        await OFFICIALHACKER .send_message(kek, "CHODAA GHARR")
        await OFFICIALHACKER .send_message(kek, "TAKK")
        await OFFICIALHACKER .send_message(kek, "APNII CHUTT")
        await OFFICIALHACKER .send_message(kek, "PAKADD")
        await OFFICIALHACKER .send_message(kek, "KEE")
        await OFFICIALHACKER .send_message(kek, "ROTII")
        await OFFICIALHACKER .send_message(kek, "GAEE HAII")
        await OFFICIALHACKER .send_message(kek, "AB BHII")
        await OFFICIALHACKER .send_message(kek, "TIME HAI")
        await OFFICIALHACKER .send_message(kek, "HUME BAAP")
        await OFFICIALHACKER .send_message(kek, "BOLDOO")
        await OFFICIALHACKER .send_message(kek, "😂")
        await OFFICIALHACKER .send_message(kek, "AISE BHII")
        await OFFICIALHACKER .send_message(kek, "TUMHARII MAA")
        await OFFICIALHACKER .send_message(kek, "TO ROZZ HUMSEE")
        await OFFICIALHACKER .send_message(kek, "CHUDTI HI HAII")
        await OFFICIALHACKER .send_message(kek, "ROZZ KALAPTI HAII")
        await OFFICIALHACKER .send_message(kek, "WO DEKHO")
        await OFFICIALHACKER .send_message(kek, "TERA BAAP")
        await OFFICIALHACKER .send_message(kek, "BETHA HAI")
        await OFFICIALHACKER .send_message(kek, "GHODEE PEE")
        await OFFICIALHACKER .send_message(
            kek,
            "TERI GANND TOD DI JAYEGI MADDRCHOD TUMHARA BAAP HU ME OFFICIAL HACKER  WALE GANND FAAD KE RAKH DENGE TERI MADARCHOOD",
        )
        await OFFICIALHACKER .send_message(kek, "TUMHARII")
        await OFFICIALHACKER  .send_message(kek, "MAA")
        await OFFICIALHACKER  .send_message(kek, "MEREEE")
        await OFFICIALHACKER  .send_message(kek, "LODEEE")
        await OFFICIALHACKER  .send_message(kek, "OHH YEAHHH")
        await OFFICIALHACKER  .send_message(kek, "KYAA MASTT")
        await OFFICIALHACKER  .send_message(kek, "MAZAA DETI")
        await OFFICIALHACKER  .send_message(kek, "HAII")
        await OFFICIALHACKER  .send_message(kek, "TUMHARII MAA")
        await OFFICIALHACKER  .send_message(kek, "OFFICIAL HACKER  NE TUMHARI BHN KO PURII RAT CHOXDAAA ")
        await OFFICIALHACKER  .send_message(kek, "😂")
        await OFFICIALHACKER  .send_message(kek, "TERI MAKI CHOOT 3 BAAR")
        await OFFICIALHACKER  .send_message(kek, "BAAP HAII H HUM")
        await OFFICIALHACKER  .send_message(kek, "TERII MAA")
        await OFFICIALHACKER  .send_message(kek, "KOO")
        await OFFICIALHACKER  .send_message(kek, "BHUTT GANDAA CHODAA")
        await OFFICIALHACKER  .send_message(kek, "BHOXDIKE AUKAAT BNA FRR OFFICIAL HACKER  SE PANGE LENA")
        await OFFICIALHACKER  .send_message(kek, "GANDUUU")
        await OFFICIALHACKER  .send_message(kek, "KIII MAAA")
        await OFFICIALHACKER  .send_message(kek, "KIII CHUTTT")
        await OFFICIALHACKER  .send_message(kek, "LETE SAMAY")
        await OFFICIALHACKER  .send_message(kek, "USKII")
        await OFFICIALHACKER  .send_message(kek, "CHUTTT")
        await OFFICIALHACKER  .send_message(kek, "MEEE MAINEE")
        await OFFICIALHACKER  .send_message(kek, "GARAM LOHEE")
        await OFFICIALHACKER  .send_message(kek, "KAA SARIYAA")
        await OFFICIALHACKER  .send_message(kek, "DAAL DIYAA")
        await OFFICIALHACKER  .send_message(kek, "KALAP GYII")
        await OFFICIALHACKER  .send_message(
            kek, "TERI BHN KE GORE BOOBS AAHAAH AAH AAHA AAAHA AAHA AAAHH"
        )
        await OFFICIALHACKER  .send_message(kek, "TERI MA KI CHOOXT FAD DI MENE BHOOSSDIKE ")
        await OFFICIALHACKER  .send_message(kek, "TERE BAAP")
        await OFFICIALHACKER  .send_message(kek, "RHEGE HUM")
        await OFFICIALHACKER  .send_message(kek, "HUMESAA")
        await OFFICIALHACKER  .send_message(kek, "ROZZ TMHARIII")
        await OFFICIALHACKER  .send_message(kek, "MAA KOO")
        await OFFICIALHACKER  .send_message(kek, "GHODII BANAKEE")
        await OFFICIALHACKER  .send_message(kek, "CHODEEEGEE")
        await OFFICIALHACKER  .send_message(kek, "TERI GAMD TOD DI JAYEGI MADDRCHOD KIII")
        await OFFICIALHACKER  .send_message(kek, "MAAAA")
        await OFFICIALHACKER  .send_message(kek, "CHUDD GYIII")
        await OFFICIALHACKER  .send_message(kek, "😂")
        await OFFICIALHACKER  .send_message(kek, "TERA ASLIII")
        await OFFICIALHACKER  .send_message(kek, "BAAAP")
        await OFFICIALHACKER  .send_message(kek, "MAIN HI HUINN YASH")
        await OFFICIALHACKER  .send_message(kek, "MERAA NAJAYAZ🤣")
        await OFFICIALHACKER  .send_message(kek, "BETA HAI TUU")
        await OFFICIALHACKER  .send_message(
            kek, "TERI MAA KI CHUUTTT AHHHH GZB BHSODDA BNA DIYAA"
        )
        await OFFICIALHACKER  .send_message(
            kek, "HUMSE BAKCHODI NA KRRR TELE PR RHNE LAYAK NHI BACHEGA"
        )
        await OFFICIALHACKER  .send_message(kek, "MAAADDRRCHHHOOODD")
        await OFFICIALHACKER  .send_message(kek, "LOOWDEE KEE BAAL")
        await OFFICIALHACKER  .send_message(kek, "LAAWDDDEEE KEE BAAL")
        await OFFICIALHACKER  .send_message(kek, "JHHAAATTT SEE SHAKAL KE")
        await OFFICIALHACKER  .send_message(kek, "CHINARRR MADRCHODDD")
        await OFFICIALHACKER  .send_message(kek, "RAMDI KI AULAAD")
        await OFFICIALHACKER  .send_message(kek, "TERRIII MAAA KO TERE SAMNE CHOODTA HU")
        await OFFICIALHACKER  .send_message(kek, "BSSDDKKEE BAAP SE PANGE LENGE")
        await OFFICIALHACKER  .send_message(kek, "YEEE LODDUUU KE BAAL")
        await OFFICIALHACKER  .send_message(kek, "JHHAAATTT BHAR KI AAUUKAAT NHI H")
        await OFFICIALHACKER  .send_message(
            kek, "AAYYYY HHHHH BAAAAPPP SSSEEE BHIIIDDHNEE MADARCHHHHOODDD"
        )
        await OFFICIALHACKER  .send_message(
            kek, "BBHHOOSSDDDIIKEEEE APNIII MAA KO DWAI LAA KRRRR DEE"
        )
        await OFFICIALHACKER  .send_message(
            kek,
            "MAADDRRRCCCHHHOOODDDD TERIIII MAA KIII CCCHHHUUUTTT SSSEEE KHUUNNN NIKALLLL DIYAA HH BBEETTIICCHHOODD",
        )
        await OFFICIALHACKER  .send_message(kek, "CHAKKKAAA HHH TUUUU MAAADDRRCHHHOODDDD")
        await OFFICIALHACKER  .send_message(kek, "JJHHHAAATEEE JITNI")
        await OFFICIALHACKER  .send_message(kek, "BHIIIII BAAADDIII HOO")
        await OFFICIALHACKER  .send_message(kek, "RHHHTTAAAA LUNNNNNDD KEEE NICHEE HI HHHH")
        await OFFICIALHACKER  .send_message(kek, "BETICCCHHOOODD")
        await OFFICIALHACKER  .send_message(
            kek, "BHHHHOOOSSSDDIIIIKKEEEE TEEERRIIII AAUUKKAAAT MERA MUUUTT"
        )
        await OFFICIALHACKER .send_message(kek, "PIINEEE KI HHHH USSEEE PIII OR KKKHUUSSHHH")
        await OFFICIALHACKER .send_message(kek, "RAHHHH BETIIICHHOOODDD CHIINARRR")
        await OFFICIALHACKER .send_message(kek, "AAJJJ KEEE BAAD OFFICIAL HACKER  SE PANGA")
        await OFFICIALHACKER .send_message(kek, "MATTT LEENNAA MADRCHOODDD")
        await OFFICIALHACKER .send_message(kek, "NHIII TTOO AGLA")
        await OFFICIALHACKER .send_message(kek, "NUMBERRR TERE PURI KHANDANNN")
        await OFFICIALHACKER .send_message(kek, "KIIII ORRTEEEE KAA HOGAAA")
        await OFFICIALHACKER .send_message(kek, "CHINNARRRR BHOSDIKAAA")
        await OFFICIALHACKER .send_message(kek, "OFFICIAL HACKER  SE H BHNCCHOOODDDD")
        await OFFICIALHACKER .send_message(kek, "YAHIII PATAKKK KR")
        await OFFICIALHACKER .send_message(kek, "CHHHOOOODDDD DENGE")
        await OFFICIALHACKER .send_message(kek, "TUMMM JESEE KITNOOO")
        await OFFICIALHACKER .send_message(kek, "KOOO CHOOOOOOODDDDD KRRR CHOD DIYAA GANDUUU")
        await OFFICIALHACKER .send_message(
            kek,
            "TELEGRAM ME RAHNA HAI TO OFFICIAL HACKER  KO PAPA BOLNA PAREGA WARNA TUMHARII BHN CHODEGI AISE HI ROJ",
        )


CmdHelp("gali").add_command("abuse", None, "Use And See To Stop .reload").add()
